# Generated by Django 4.1.3 on 2022-11-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0005_category_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='products/')),
                ('unit', models.CharField(max_length=40)),
                ('guarantee', models.SmallIntegerField()),
                ('delivery', models.SmallIntegerField()),
                ('availabilty', models.CharField(max_length=40)),
                ('chegirma_true', models.BooleanField()),
                ('chegirma', models.IntegerField(blank=True, null=True)),
                ('recommended', models.BooleanField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
    ]
