# Generated by Django 4.1.3 on 2022-11-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='street',
        ),
        migrations.RemoveField(
            model_name='account',
            name='zip_code',
        ),
    ]
