# Generated by Django 4.1.3 on 2022-11-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_city_remove_account_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
