# Generated by Django 4.1.3 on 2022-11-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_city_account_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='ph_num',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
