# Generated by Django 4.1.3 on 2022-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.FileField(null=True, upload_to='subcategory/'),
        ),
    ]
