# Generated by Django 4.1.3 on 2022-11-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recommended',
            field=models.BooleanField(null=True),
        ),
    ]
